[workspace]
members = [
    "packages/decrypt-core",
    "packages/decrypt-wasm"
]
resolver = "2"

[workspace.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
aes = "0.8"
ecb = "0.1"
